// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-northeast-2",
    "aws_cognito_identity_pool_id": "ap-northeast-2:fd03d837-6219-45b9-b91a-a8d05f16eee0",
    "aws_cognito_region": "ap-northeast-2",
    "aws_user_pools_id": "ap-northeast-2_Hl72waweo",
    "aws_user_pools_web_client_id": "hdag28vn53fqv200eu24cvrn0",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "ap-northeast-2",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "amplifyshopitems-master",
            "region": "ap-northeast-2"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "amplifyshopapi",
            "endpoint": "https://g0novd2p23.execute-api.ap-northeast-2.amazonaws.com/master",
            "region": "ap-northeast-2"
        }
    ],
    "aws_mobile_analytics_app_id": "1ccf4045c6cf48dca858a0e387710ce2",
    "aws_mobile_analytics_app_region": "us-west-2"
};


export default awsmobile;
